theme: jekyll-theme-cayman
# theme: jekyll-theme-architect

plugins:
  - jekyll-readme-index

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

exclude:
  - "ipfshash"
  - "ndns.sh"
  - "Gemfile"
  - "Gemfile.lock"
  # - "README.md"
  # - "package.json"
  # - "package-lock.json"
  # - "LICENSE.txt"
  # - "lib/"
  # - "_compress_images_cache.yml"
