name: CI

on:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run check version TorrServer
      run: |
        old_version=$(cat README.md | grep Version | awk '{print $2}')
        new_version=$(curl -s "https://github.com/YouROK/TorrServer/releases/latest" | sed 's#.*tag/\(.*\)\".*#\1#')
        echo "old_version=$old_version" >> $GITHUB_ENV
        echo "new_version=$new_version" >> $GITHUB_ENV
        [[ "$old_version" == "$new_version" ]] && echo $old_version && exit || sed -i "s/$old_version/$new_version/" README.md
    - name: Commit files
      if: ${{ env.old_version != env.new_version }}
      run: |
        git config --local user.email "mailcreio@gmail.com"
        git config --local user.name "creio"
        git add .
        git commit -am "$(date +%d.%m.%Y) Update $new_version"
        git push
