name: IPFS Deploy
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "22 22 * * *"
  repository_dispatch:
    types: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Bundler Cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build & Deploy to GitHub Pages
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
    - name: Save built site for deployment
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: |
          _site
          ipfshash
          ndns.sh

  deploy-ipfs:
    runs-on: ubuntu-latest
    needs: build
    env:
      NPM_PACKAGES: .npm_packages
      NETLIFY_KEY: ${{secrets.NETLIFY_API_KEY}}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Setup non-root `npm install -g`
        run: |
          mkdir ~/$NPM_PACKAGES
          npm config set prefix ~/$NPM_PACKAGES
      - name: Update PATH
        uses: myci-actions/export-env-var@1
        with:
          name: PATH
          value: $PATH:$HOME/$NPM_PACKAGES/bin
      - name: Restore cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/${{ env.NPM_PACKAGES }}
          key: ${{ runner.os }}-ipfs-deploy
      - name: Install ipfs-deploy
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g ipfs-deploy
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Run ipfs-deploy
        run: |
          [[ -f public/ipfshash ]] || touch public/ipfshash
          old_ipfs_hash=$(cat public/ipfshash)
          cat public/ipfshash
          ls cat public
          ipfs-deploy -C -O -p infura public > public/ipfshash
          new_ipfs_hash=$(cat public/ipfshash)
          echo "old_ipfs_hash=$old_ipfs_hash" >> $GITHUB_ENV
          echo "new_ipfs_hash=$new_ipfs_hash" >> $GITHUB_ENV
      - name: Run netlify dns
        if: ${{ env.old_ipfs_hash != env.new_ipfs_hash }}
        run: |
          bash public/ndns.sh $new_ipfs_hash $NETLIFY_KEY

  delete-artifacts:
    runs-on: ubuntu-latest
    if: always()
    needs:
    - deploy-ipfs
    steps:
      - name: Delete saved build artifacts
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: public
          failOnError: false
