name: IPFS Deploy
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "22 22 * * *"
  repository_dispatch:
    types: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Bundler Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build & Deploy to GitHub Pages
        uses: creio/jekyll-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      - name: Save built site for deployment
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: |
            _site
            ndns.sh

  deploy-ipfs:
    runs-on: ubuntu-latest
    needs: build
    env:
      NPM_PACKAGES: .npm_packages
      NETLIFY_KEY: ${{secrets.NETLIFY_API_KEY}}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Setup non-root `npm install -g`
        run: |
          mkdir ~/$NPM_PACKAGES
          npm config set prefix ~/$NPM_PACKAGES
      - name: Update PATH
        uses: myci-actions/export-env-var@1
        with:
          name: PATH
          value: $PATH:$HOME/$NPM_PACKAGES/bin
      - name: Restore cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/${{ env.NPM_PACKAGES }}
          key: ${{ runner.os }}-ipfs-deploy
      - name: Install ipfs-deploy
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g ipfs-deploy
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Run ipfs-deploy
        run: |
          old_ipfs_hash=$(bash public/ndns.sh $NETLIFY_KEY)
          new_ipfs_hash=$(ipfs-deploy -C -O -p infura public/_site)
          echo "old_ipfs_hash=$old_ipfs_hash" >> $GITHUB_ENV
          echo "new_ipfs_hash=$new_ipfs_hash" >> $GITHUB_ENV
      - name: Run netlify dns
        if: ${{ env.old_ipfs_hash != env.new_ipfs_hash }}
        run: |
          bash public/ndns.sh $NETLIFY_KEY $new_ipfs_hash

  delete-artifacts:
    runs-on: ubuntu-latest
    if: always()
    needs:
    - deploy-ipfs
    steps:
      - name: Delete saved build artifacts
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: public
          failOnError: false
