name: IPFS Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Save built site for deployment
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: ./

  deploy-ipfs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Restore cache
        id: cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-ipfs-deploy
      - name: Install ipfs-deploy
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g ipfs-deploy
      - name: Download saved site
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Run ipfs-deploy
        run: ipfs-deploy -C -O -p infura public

  delete-artifacts:
    runs-on: ubuntu-latest
    if: always()
    needs:
    - deploy-ipfs
    steps:
      - name: Delete saved build artifacts
        uses: GeekyEggo/delete-artifact@v1.0.0
        with:
          name: public
          failOnError: false
