name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v1
      id: upload
      with:
        path: ./
        protocol: https
        timeout: 60000
        verbose: true
    - name: Up dns
      env:
        ipfs_hash: ${{ steps.upload.outputs.hash }}
        USERNAME: github-actions[bot]
      run: |
        old_version=$(cat README.md | grep Version | awk '{print $2}')
        echo $ipfs_hash
        echo
        echo $old_version
